language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://test.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "KfqDSXWI4OqhFsj0HeVUFJcnUyqVM4EOcAvDG5JejR8kii2qa9pTboqevs9sv/suyVJamer1l/XSXG81z93tux7NvVvH5GJfonmsUP0QOxMniEPlreXoxhu3aWQe17bnemyJEJbeLb9RHGosPorPrUzkCM76hTl7P9QD7/x3FeLm2atu9qk/c/zlS+9zdzMWD+k0AxZQJbIQHGmCuS3ukxlIUZxOqLwzJ/4puQwyk1YD7xM8j6JppNP3tcVSacAgtJYwzQ1nrQNkyw+cxAUdPA5piZnnp1jUswOCcHFoDmzhFc6Fe4Ee8F6QfBn8krW0LpPJwooDRs5EruK57Y/FSfZVJyL3is7SiZ/Z47Eko9TLQdCv8YkM+B8DEQPKZCN4c/9CDJiJwFKhc3RLLyRtNNBNumD8oHsWATG12RYgAduF8khXV/fsgKfQVDYXcoZfj/YQxZLsugqvzRpQfngpmD+/1jxQLWrOG0a5oKUYpn2u3WtNlySZ2SIvhkRWNPCLuGevACyCxS67g2xDPKDkQRBHU+zTZLsGy01bAcllvIN76LuhJizdZ50M4uj6wFOQhtnvUF/72AIk0WLwzNHL9+Cxe4m/au6fQaMOzdHDIad+IiAAt0x0u7AvECCRsTtIJZBCghudLDeVHqL0Iz6EG0tBaWIh9fx+gutTiolU+TI="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
